import * as L from './lucide';

export const sharedIcons = {
  // Main modules
  Dashboard: L.LayoutDashboard,
  Analytics: L.BarChart2,
  School: L.School,
  Communications: L.Mail,
  KnowledgeBase: L.BookOpen,
  ConciergeAI: L.Bot,
  CRM: L.Users,
  Marketplace: L.Store,
  SystemSettings: L.Settings,
  
  // UI
  ToggleSidebar: L.PanelLeft,
  ToggleSidebarRight: L.PanelRight,
  Search: L.Search,
  Close: L.X,
  Time: L.Clock,
  AlertCircle: L.AlertCircle,
  Loader2: L.Loader2,
  
  // Overlays / Dock
  News: L.Newspaper,
  Chat: L.MessageSquare,
  Cloud: L.Cloud,
  Canva: L.Palette,
  Coder: L.Code2,
  Office: L.FileText,
  Video: L.Clapperboard,
  Gamification: L.Gamepad2,
  Lifestyle: L.HeartPulse,
  Hobbies: L.Bike,
  Media: L.Music,
  Tv: L.Tv,
  Studio: L.Camera,
  
  // Common icons
  ChevronRight: L.ChevronRight,
  ChevronLeft: L.ChevronLeft,
  Users: L.Users,
  User: L.User,
  Security: L.Shield,
  Briefcase: L.Briefcase,
  Students: L.GraduationCap,
  Administration: L.Users,
  Curriculum: L.BookCopy,
  Library: L.Library,
  SystemPrompts: L.Lightbulb,
  UsageAnalytics: L.Cpu,
  Storefront: L.ShoppingBag,
  Orders: L.Truck,
  Send: L.SendHorizontal,
  ClipboardCheck: L.ClipboardCheck,
  Goal: L.Goal,
  
  // Analytics Module aliases
  Branding: L.BrandingIcon,
  Overview: L.BarChartHorizontal,
  Finance: L.DollarSign,
  Marketing: L.TrendingUp,
  
  // Other generic re-exports from original file
  Activity: L.Activity,
  Megaphone: L.Megaphone,
  Wand2: L.Wand2,
  PenSquare: L.PenSquare,
  Siren: L.Siren,
  BrainCircuit: L.BrainCircuit,
  TrendingUp: L.TrendingUp,
  BookOpen: L.BookOpen,
  ScanLine: L.ScanLine,
  Lightbulb: L.Lightbulb,
  Image: L.Image,
  Upload: L.Upload,
  Save: L.Save,
  UserPlus: L.UserPlus,
  View: L.View,
  Trash2: L.Trash2,
  Smartphone: L.Smartphone,
  PlusCircle: L.PlusCircle,
  Plus: L.Plus,
  Minus: L.Minus,
  Edit: L.Edit,
  MoreVertical: L.MoreVertical,
  Check: L.Check,
  Eye: L.Eye,
  Download: L.Download,
  PlayCircle: L.PlayCircle,
  TrendingDown: L.TrendingDown,
  CheckCircle: L.CheckCircle,
  MousePointer2: L.MousePointer2,
  Type: L.TypeIcon,
  StickyNote: L.StickyNote,
  Undo: L.Undo,
  Redo: L.Redo,
  Facebook: L.Facebook,
  Twitter: L.Twitter,
  Award: L.Award,
  Shield: L.Shield,
  Cpu: L.Cpu,
  GraduationCap: L.GraduationCap,
  Heart: L.Heart,
  Sparkles: L.Sparkles,
  Smile: L.Smile,

  // New Icons for enhancements
  Pin: L.Pin,
  PinOff: L.PinOff,
  AlertTriangle: L.AlertTriangle,
  CalendarDays: L.CalendarDays,
  Book: L.BookCopy,
  History: L.History,
  Revert: L.Undo2,
  Home: L.Home,
  Printer: L.Printer,
  MapPin: L.MapPin,
  Instagram: L.Instagram,
  Bell: L.Bell,
  Languages: L.Languages,
  Swords: L.Swords,
  Trophy: L.Trophy,

  // Window management
  Minimize: L.Minus,

  // Icons for Studio
  Design: L.Palette,
  VideoL1: L.VideoIcon,
  CoderL1: L.Code2,
  OfficeL1: L.FileText,
  Word: L.FileIcon,
  Excel: L.Sheet,
  PowerPoint: L.PresentationIcon,
  Diagram: L.Share2,
  Bold: L.Bold,
  Italic: L.Italic,
  Underline: L.Underline,
  AlignLeft: L.AlignLeft,
  AlignCenter: L.AlignCenter,
  AlignRight: L.AlignRight,
  Rectangle: L.RectangleHorizontal,
  Circle: L.Circle,
  Diamond: L.Diamond,
  ArrowRight: L.ArrowRight,
  LayoutTemplate: L.LayoutTemplate,
  Shapes: L.Shapes,
  UploadCloud: L.UploadCloud,
  Folder: L.Folder,
  Triangle: L.Triangle,
  Star: L.Star,
  Frame: L.Frame,
  Palette: L.Palette,
  Heading1: L.Heading1,
  Heading2: L.Heading2,
  Heading3: L.Heading3,
  Layers: L.LayersIcon,
  AlignHorizontalJustifyCenter: L.AlignHorizontalJustifyCenter,
  AlignHorizontalJustifyLeft: L.AlignHorizontalJustifyStart,
  AlignHorizontalJustifyRight: L.AlignHorizontalJustifyEnd,
  AlignVerticalJustifyStart: L.AlignVerticalJustifyStart,
  AlignVerticalJustifyCenter: L.AlignVerticalJustifyCenter,
  AlignVerticalJustifyEnd: L.AlignVerticalJustifyEnd,
  Group: L.Group,
  Ungroup: L.Ungroup,
  ZoomIn: L.ZoomIn,
  ZoomOut: L.ZoomOut,
  Expand: L.Expand,
  DownloadCloud: L.DownloadCloud,
  Lock: L.Lock,
  Unlock: L.Unlock,
  EyeOff: L.EyeOff,
  Copy: L.Copy,
  FilePlus2: L.FilePlus2,
  bringToFront: L.BringToFront,
  sendToBack: L.SendToBack,

  // Icons for Video Editor
  Captions: L.Captions,
  Ratio: L.Ratio,
  Scissors: L.Scissors,
  Rewind: L.Rewind,
  FastForward: L.FastForward,
  Play: L.Play,
  Pause: L.Pause,
  Mic: L.Mic,
  Fullscreen: L.Fullscreen,
  GripVertical: L.GripVertical,
  Animation: L.Wind,
  Speed: L.Gauge,
  Basic: L.SlidersHorizontal,
  Background: L.Image,
  Position: L.Move,
  ScaleIcon: L.Scale,
  Rotation: L.RotateCw,
  AddTrack: L.PlusSquare,


  // Add direct access to icons to fix errors
  Store: L.Store,
  Settings: L.Settings,
  FileText: L.FileText,
  Music: L.Music,
  BookCopy: L.BookCopy,
  PieChart: L.PieChart,
  BarChart: L.BarChart,
  BarChart2: L.BarChart2,
  BarChart3: L.BarChart3,
  List: L.List,
  LogIn: L.LogIn,
  LogOut: L.LogOut,
  Map: L.Map,
  Crosshair: L.Crosshair,
  ShoppingCart: L.ShoppingCart,
  Globe: L.Globe,
  UserCog: L.UserCog,
  Puzzle: L.Puzzle,
  CreditCard: L.CreditCard,
  Wallet: L.Wallet,
  BookLock: L.BookLock,
  KeyRound: L.KeyRound,
  Webhook: L.Webhook,
  Calculator: L.Calculator,
  FlaskConical: L.FlaskConical,
  Computer: L.Laptop,
  Filter: L.Filter,
  Bookmark: L.Bookmark,
  Ticket: L.Ticket,
  Package: L.Package,
  MinusCircle: L.MinusCircle,
  Radius: L.Radius,
};